services:
  - type: web
    name: letsstudy-api
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt && flask db upgrade head
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true