"""initial migration

Revision ID: 94d57a9ce9f4
Revises: 
Create Date: 2026-03-12 23:59:18.739202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d57a9ce9f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('institutions',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('national_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('user_category', sa.String(length=32), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id')
    )
    op.create_table('study_groups',
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_study_groups_course_id_courses')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], name=op.f('fk_study_groups_owner_user_id_users')),
    sa.PrimaryKeyConstraint('study_group_id')
    )
    op.create_table('memberships',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('date_graduated', sa.DateTime(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.study_group_id'], name=op.f('fk_memberships_study_group_id_study_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.study_group_id'], name=op.f('fk_reviews_study_group_id_study_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('studygroup_institution',
    sa.Column('study_group_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], name=op.f('fk_studygroup_institution_institution_id_institutions')),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.study_group_id'], name=op.f('fk_studygroup_institution_study_group_id_study_groups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studygroup_institution')
    op.drop_table('reviews')
    op.drop_table('memberships')
    op.drop_table('study_groups')
    op.drop_table('users')
    op.drop_table('institutions')
    op.drop_table('courses')
    # ### end Alembic commands ###
